as.data.frame(Titanic)
head(data.frame(Titanic)
library(dplyr)
data.frame(Titanic)%>%select(sex,survivded)
select_sex_survivded <- select(data.frame(Titanic), Sex, Survived)
head(select_sex_survivded)
select_survivded <- select(select_sex_survivded, -Sex)
head(select_survivded)
rename(data.frame(Titanic), Gender = Sex )
new_data.frame<- data.frame(Titanic)
new_data.frame$gender <-new_data.frame$Sex
head(new_data.frame)
new_data.frame_male<- filter(new_data.frame, Sex == "Male")
head(new_data.frame_male)
new_data_arange <- arrange(new_data.frame, gender)
head(new_data_arange)
examined <- sum(new_data_arange$Freq)
print(examined) 2201
new_data_females <- filter(new_data.frame, Sex == "Female")
head(new_data_females)
new_male_female <- union(new_data.frame_male, new_data_females)
head(new_male_female)
tail(new_male_female)